--CAU1.1
SELECT IIF(LUONG>=LTB,'KHONG TANG LUONG','TANG LUONG') AS THUONG,TENNV,LUONG,LTB
FROM (SELECT TENNV,LUONG,LTB
FROM NHANVIEN,(SELECT PHG,AVG(LUONG) AS 'LTB' FROM NHANVIEN GROUP BY PHG) AS TEMP 
WHERE NHANVIEN.PHG=TEMP.PHG) AS ABC

--CAU1.2
SELECT IIF(LUONG>30000,'truong phong','nhan vien')
as ChucVu,TENNV,LUONG
FROM NHANVIEN

--CAU1.3
SELECT TENNV=CASE PHAI
WHEN 'Nam' THEN 'MR.'+[TENNV]
WHEN N'Nữ'THEN 'MS.'+[TENNV]
END
FROM NHANVIEN

--CAU1.4
SELECT TENNV,LUONG,THUE = CASE
WHEN LUONG BETWEEN 0 AND 25000 THEN LUONG*0.1
WHEN LUONG BETWEEN 25000 AND 30000 THEN LUONG*0.12
WHEN LUONG BETWEEN 30000 AND 40000 THEN LUONG*0.13
WHEN LUONG BETWEEN 40000 AND 50000 THEN LUONG*0.2
else LUONG*0.25
END
FROM NHANVIEN

--CAU2.1
SELECT HONV, TENNV
FROM NHANVIEN
WHERE MANV%2=0 

--CAU2.2
SELECT HONV, TENNV
FROM NHANVIEN
WHERE MANV%2=0 AND MANV!=4 

--CAU3.1
BEGIN TRY
INSERT PHONGBAN
VALUES (799, 'ZXK-799','2008-07-01','0197-05-22')
PRINT 'SUCCESS: RECORD WAS INSERTED'
END TRY

BEGIN CATCH
PRINT'FAILURE: RECORD WAS NOT INSERTED.'
PRINT ' ERROR'+ CONVERT(VARCHAR,ERROR_NUMBER(),1)
+': ' + ERROR_MESSAGE()
END CATCH

--CAU3.2
BEGIN TRY
DECLARE @RESULT INT
SET @RESULT = 55/0
END TRY
BEGIN CATCH 
DECLARE 
@ERMESSAGE NVARCHAR(2480),
@ERSEVERITY INT,
@ERSTATE INT
SELECT 
@ERMESSAGE = ERROR_MESSAGE(),
@ERSEVERITY = ERROR_SEVERITY(),
@ERSTATE = ERROR_STATE()
RAISERROR(@ERMESSAGE,
          @ERSEVERITY,
		  @ERSTATE)
END CATCH
