  USE QLDA
  /**CÂU 1.1**/
  GO
  SELECT*, 
  CAST(THOIGIAN AS int) AS intTHỜIGIAN,
  CAST(THOIGIAN AS decimal(5,2)) AS decTHỜIGIAN,
  CONVERT(decimal (5,2),THOIGIAN) AS dec1THỜIGIAN
  FROM PHANCONG
  /**CÂU 1.2**/
  GO
  SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS decimal(6,2))
  FROM PHANCONG, DEAN
  
  GO
  SELECT THOIGIAN + CONVERT(decimal(6,2),101)
  FROM PHANCONG, DEAN
  
  GO
  SELECT THOIGIAN+CAST(PHANCONG.THOIGIAN AS VARCHAR)
  FROM PHANCONG, DEAN

   GO
  SELECT THOIGIAN + CONVERT(VARCHAR,101)
  FROM PHANCONG, DEAN
  /**CÂU 1.3**/
  GO
  SELECT TENPHG, AVG(LUONG) AS 'LUONG TB', 
  CAST(AVG(LUONG) AS DECIMAL(10,2)) AS 'LUONG TB CAST',
  CONVERT(decimal (10,2), AVG(LUONG)) AS 'LUONG TB CONVERT'
  FROM PHONGBAN
  GROUP BY TENPHG
  /**BÀI 2**/
  SELECT THOIGIAN as Tổngthờigian, ceiling(CAST(PHANCONG.THOIGIAN AS decimal(6,2)))
  FROM PHANCONG, DEAN

  GO
  SELECT THOIGIAN as Tổngthờigian, floor(CAST(PHANCONG.THOIGIAN AS decimal(6,2)))
  FROM PHANCONG, DEAN

  GO
  SELECT HONV+' '+TENLOT+' '+TENNV, LUONG FROM NHANVIEN
  WHERE LUONG > (SELECT ROUND(AVG(luong),2) FROM NHANVIEN WHERE PHG=(SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Nghiên cứu'))
  /**BÀI 3**/
  SELECT 
  UPPER (HONV) AS 'HONV', 
  LOWER(TENLOT) AS 'tenlot', 
  LOWER (LEFT(TENNV,1)) + UPPER(SUBSTRING(TENNV,2,1)) + SUBSTRING(TENNV,3,LEN(TENNV)-2), TENNV
  DCHI, COUNT(MANV) AS 'SỐ THÂN NHÂN' FROM NHANVIEN
  GROUP BY HONV, TENLOT, TENNV, DCHI HAVING COUNT(MANV) >= 2
  SELECT DCHI FROM NHANVIEN
  SELECT DCHI,CHARINDEX(' ',DCHI) FROM NHANVIEN
  SELECT DCHI, LEFT(DCHI,CHARINDEX(' ',DCHI)) AS 'SỐ NHÀ'FROM NHANVIEN
  /**BÀI 4**/
  SELECT YEAR(GETDATE()) - YEAR(NGSINH) AS 'TUOI' FROM NHANVIEN
  SELECT CONVERT(VARCHAR, NGSINH,105) AS 'NGAY SINH' FROM NHANVIEN