--cau1
DECLARE @MAX_LUONG float
SELECT @MAX_LUONG=MAX(LUONG)
FROM NHANVIEN

SELECT *
FROM NHANVIEN
WHERE LUONG=@MAX_LUONG

--cau2
DECLARE @AVGLUONG float
SELECT @AVGLUONG=AVG(LUONG)
FROM NHANVIEN
SELECT HONV,TENLOT,TENNV
FROM NHANVIEN
WHERE (LUONG>@AVGLUONG) AND (PHG = 5)

--cau3
DECLARE @AVGLUONG FLOAT
SELECT  @AVGLUONG=AVG(LUONG)
FROM NHANVIEN
SELECT TENPHG,COUNT (*) AS SOLUONG
FROM PHONGBAN,NHANVIEN
WHERE  MAPHG =PHG 
GROUP BY TENPHG
HAVING @AVGLUONG>30000
--cau4
SELECT TENPHG,COUNT (*) AS SOLUONG
FROM PHONGBAN,DEAN
WHERE  MAPHG =PHONG
GROUP BY TENPHG